version: "3.9"

services:
  postgres:
    container_name: postgresql
    build: ./Postgresql
    ports:
      - 5432:5432
    networks:
      - transcend
    env_file:
      - .env
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: ./dockerfile/Dockerfile
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3004:3004
      - 3005:3005
    networks:
      - transcend
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: ./dockerfile/Dockerfile
    ports:
      - 4200:80
    networks:
      - transcend
    restart: unless-stopped
    depends_on:
      - backend


volumes:
  database:

networks:
  transcend: