version: "3.9"

services:
  postgres:
    container_name: postgresql
    build: ./requirements/postgresql
    ports:
      - 5432:5432
    networks:
      - transcend
    env_file:
      - .env
    restart: unless-stopped
      

  backend:
    build:
      dockerfile: ./requirements/backend/Dockerfile
    ports:
      - 3001:3001
    networks:
      - transcend
    volumes:
      - ../../Backend:/app
    restart: unless-stopped
    depends_on:
      - postgres


volumes:
  database:

networks:
  transcend: