version: "3.9"

services:
  postgres:
    healthcheck:
        test: "PGPASSWORD=${POSTGRES_PASSWORD} psql -U ${POSTGRES_USER} -w -d ${DB_NAME} -c 'select 1;'"
        interval: 2s
        retries: 120
        timeout: 10s
    container_name: postgresql
    build: ./requirements/postgresql
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped
#   backend:
#     build:
#       dockerfile: ./requirements/backend/Dockerfile
#     ports:
#       - 3001:3001
#     networks:
#       - backend
#     volumes:
#       - ../../Backend:/app
#     restart: unless-stopped

volumes:
  data:

networks:
  backend: