version: "3.9"

services:
  postgres:
    container_name: postgresql
    build: ./requirements/postgresql
    ports:
      - 5432:5432
    networks:
      - transcend
    env_file:
      - .env
    restart: unless-stopped

volumes:
  database:

networks:
  transcend: